### ISSUE TITLE
can you write a todo 

### ISSUE THREAD

**Issue by gillesguillaume99** [lolwheel/OWEnhancer#3]
Hello , 
First i will congratulate you for your work and to have share it! I think that's realy usefull.
I'm onewheel owner , i'm in a Belgium group of onewheeler.
I'm little knowledge on arduino,esp.
We are many to have mistake with board ( maybe to swap board and repair ) , or have add a battery (to a have a good reading).
I hope help my community with your project , and maybe help you with report..
If you can write a todo to inject all data in the wemos, normaly i code for my own i use only the library from other, i never use a entire code of other. 
Thanks anyway , best regard.

**Comment by lolwheel** [comment]
Don't mean to be condescending at all but at this point this project isn't of much use to anyone who doesn't know how to flash an ESP8266 chip.

I'll write up that section once I have battery percentage remapping implemented. In the meantime you can try looking up that info online yourself, ESP8266 is an extremely popular chip and there are hundreds of articles about getting started with them.
