### ISSUE TITLE
Scope of this project - some additional ideas for features

### ISSUE THREAD

**Issue by jrwrodgers** [lolwheel/OWEnhancer#6]
I've made q schematic of how I understand this system to work currently and wondered whether this could be extended with the following features:

1) Current sensor to measure actual current draw and sum mAH usage. This should lead to a more accurate battery remaining and a live current draw.
2) Additional input for second BMS - perhaps from an external battery extended unit
3) An App over BLE - Battery health, usage, individual cells, temps, mAH remaining. Alarm for current draw? No more unexpected low battery nose dives?

Is my understanding of this system through the schematic correct?
Do you think these would be interesting features to develop with the project?

Thanks

![OWE](https://user-images.githubusercontent.com/6489861/150109601-06b3b5c5-5528-42e0-a1e7-74bebc643c64.png)

**Comment by lolwheel** [comment]
Nice graph. For now this falls out of the scope that I've designated for this project.

Some tips - if you splice the external battery before the FM BMS, the current sensor on that board will report actual consumed Ahs so no new hardware will be necessary.

I did try using an ESP32 chip but the BMS power supply wasn't able to provide enough power to keep it up, the whole BMS was restarting when I would turn either WiFI or Bluetooth modem on.

There's some chance that the main controller voltage regulator might be able to provide enough power but I'm focusing on an ESP8266 based solution for now as that's what I have in my Onewheel.
